USE SRO_VT_PROXY
GO
TRUNCATE TABLE [dbo]._AutoNotice
TRUNCATE TABLE [dbo]._AutoTeleport
TRUNCATE TABLE [dbo]._CharLocked
TRUNCATE TABLE [dbo]._Event_TaiXiu
TRUNCATE TABLE [dbo]._Event_TaiXiuSoiCau
TRUNCATE TABLE [dbo]._Event_XSMB
TRUNCATE TABLE [dbo]._Event_XSMB_LOG
TRUNCATE TABLE [dbo]._LoadImageTimeSpan
TRUNCATE TABLE [dbo]._LogAllChat
TRUNCATE TABLE [dbo]._LogCharStatusChange
TRUNCATE TABLE [dbo]._LogGlobalChat
TRUNCATE TABLE [dbo]._LogGMChat
TRUNCATE TABLE [dbo]._LogGUILDChat
TRUNCATE TABLE [dbo]._LogPMChat
TRUNCATE TABLE [dbo]._LogPTChat
TRUNCATE TABLE [dbo]._LogUNIONChat
TRUNCATE TABLE [dbo]._LogUniqueKills
TRUNCATE TABLE [dbo]._MagicPop_Stats
TRUNCATE TABLE [dbo]._Players
TRUNCATE TABLE [dbo]._ThievesStackRecords
TRUNCATE TABLE [dbo]._TotalPointRanking
TRUNCATE TABLE [dbo]._VIP
TRUNCATE TABLE [dbo]._Wanted
TRUNCATE TABLE [dbo]._DaiLyLogin
TRUNCATE TABLE [dbo]._CharChest
TRUNCATE TABLE [dbo]._CharIconList
TRUNCATE TABLE [dbo]._CharLocked
TRUNCATE TABLE [dbo]._CharTitleColor
TRUNCATE TABLE [dbo]._DaiLyLogin
TRUNCATE TABLE [dbo]._Event_Lottery
TRUNCATE TABLE [dbo]._Event_PVP
TRUNCATE TABLE [dbo]._Event_PVP_Handle
TRUNCATE TABLE [dbo]._LogUniqueKilled
TRUNCATE TABLE [dbo]._LogUniqueEntered
TRUNCATE TABLE [dbo]._InstantBuffsDelivery
TRUNCATE TABLE [dbo]._InstantCharReloadDelivery
TRUNCATE TABLE [dbo]._InstantDmgDelivery
TRUNCATE TABLE [dbo]._InstantDropItemDelivery
TRUNCATE TABLE [dbo]._InstantExperienceDelivery
TRUNCATE TABLE [dbo]._InstantGoldDelivery
TRUNCATE TABLE [dbo]._InstantGoldLessDelivery
TRUNCATE TABLE [dbo]._InstantHwanLevelDelivery
TRUNCATE TABLE [dbo]._InstantItemDelivery
TRUNCATE TABLE [dbo]._InstantMobSpawnAtPosDelivery
TRUNCATE TABLE [dbo]._InstantMobSpawnNearPlayerDelivery
TRUNCATE TABLE [dbo]._InstantPvpStateDelivery
TRUNCATE TABLE [dbo]._InstantSilkDelivery
TRUNCATE TABLE [dbo]._InstantSkillPointDelivery
TRUNCATE TABLE [dbo]._InstantStatPointDelivery
TRUNCATE TABLE [dbo]._InstantTeleportDelivery
TRUNCATE TABLE [dbo]._InstantUpdateItemDelivery
TRUNCATE TABLE [dbo]._InstantZerkDelivery
TRUNCATE TABLE [dbo].[_BattleRoyaleCharBak]
TRUNCATE TABLE [dbo]._BattleRoyaleCharSkillBak
TRUNCATE TABLE [dbo]._BattleRoyaleCharSkillMasteryBak
TRUNCATE TABLE [dbo]._BattleRoyaleInventoryBak
TRUNCATE TABLE [dbo]._BattleRoyaleInventoryForAvatarBak
TRUNCATE TABLE [dbo]._BattleRoyaleKillCount
TRUNCATE TABLE [dbo]._BattleRoyaleClientConfigBak